/**
 * Constant file for having the constant data.
 */
export const CLICK_ACTION = "BUTTON_CLICK_ACTION";
export const CLEAR_ACTION = "BUTTON_CLEAR_ACTION";
export const LOAD_START_ACTION = "BUTTON_LOAD_START_ACTION";
export const LOAD_END_ACTION = "BUTTON_LOAD_END_ACTION";

/**
 * Dispatcher source
 */
export const CLICK_ACTION_DISPATCHER = "BUTTON_CLICK_ACTION_DISPATCHER";
export const CLEAR_ACTION_DISPATCHER = "BUTTON_CLEAR_ACTION_DISPATCHER";
export const ASYNC_LOAD_START_ACTION_DISPATCHER =
  "ASYNC_LOAD_START_ACTION_DISPATCHER";
export const ASYNC_LOAD_END_ACTION_DISPATCHER =
  "ASYNC_LOAD_END_ACTION_DISPATCHER";
/**
 * App Store event name
 */
export const CHANGE_EVENT = "CHANGE_EVENT";
